global using Api;
global using Infastructure;
global using Infastructure.Data.Extensions;
global using Microsoft.AspNetCore.Mvc;

global using Application.DtoModels;
global using Application.Exceptions;
global using Application.Topics.Queries.GetTopics;
global using MediatR;
global using Application.Topics.Commands.CreateTopic;
global using Application.Topics.Queries.GetTopic;
global using Application.Topics.Commands.DeleteTopic;
global using Application.Topics.Commands.UpdateTopic;
global using Api.Exception.Handler;
global using Application.Mapping;
global using Domain.Security;
global using Api.Security.Services;
global using Domain.Security.Dtos;
global using Microsoft.AspNetCore.Identity;
